config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :jobs

  resources :search do
    collection do
     get :list
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  require 'rest-client'
  require 'json'
  
  def index
    jobs_get = RestClient.get Rails.application.config.api_server_url + "jobs", {:params => 
        {:current_position => params[:current_position], :distance => "50", :role => "-1", :hourly_rate => "-1", 
          :contract_type => "-1", :job_type => "-1", :shift => "-1", :page => 1, :size => 20}, :Authorization => 
            Rails.application.config.api_authorization, "Content-Type" => "application/json"}

    @jobs = Hash.from_xml(jobs_get)

  end

  def show

    job_get = RestClient.get Rails.application.config.api_server_url + "jobs/job_search", 
      {:params => {:job_id => params[:id]}, :Authorization => Rails.application.config.api_authorization,
        "Content-Type" => "application/json"}
 
    @job = Hash.from_xml(job_get)["hash"]["job"]

  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def list
		
		# jobs_get = RestClient.get Rails.application.config.api_server_url + "jobs", {:params => 
  #     {:current_position => params[:current_position], :distance => params[:distance], :role => params[:job_role_id], 
  #       :hourly_rate => params[:hourly_rate], :contract_type => params[:contract_type], :job_type => params[:job_type], 
  #       :shift => params[:shift_id], :page => 1, :size => 20}, :Authorization => Rails.application.config.api_authorization, "Content-Type" => "application/json"}


	 #  job_roles_get = RestClient.get Rails.application.config.api_server_url + "job_roles", {:Authorization => Rails.application.config.api_authorization,
  #       "Content-Type" => "application/json"}

	 #  @jobs = Hash.from_xml(jobs_get)

	 #  @job_roles = Hash.from_xml(job_roles_get)

	  redirect_to :controller => 'search', :action => 'index', :anchor => 'search_results', :location => params[:location], 
	  	:current_position => params[:current_position], :distance => params[:distance], :job_role_id => params[:job_role_id], 
      :hourly_rate => params[:hourly_rate], :contract_type => params[:contract_type], :job_type => params[:job_type], 
      :shift_id => params[:shift_id]

	end

	def index
		
		# jobs_get = RestClient.get Rails.application.config.api_server_url + "jobs", {:params => 
		# 		{:current_position => params[:current_position], :distance => "50", :role => "-1", :hourly_rate => "-1", 
		# 			:contract_type => "-1", :job_type => "-1", :shift => "-1", :page => 1, :size => 20}, :Authorization => 
		# 				Rails.application.config.api_authorization, "Content-Type" => "application/json"}
		
	  jobs_get = RestClient.get Rails.application.config.api_server_url + "jobs", {:params => 
      {:current_position => params[:current_position], :distance => params[:distance], :role => params[:job_role_id], 
        :hourly_rate => params[:hourly_rate], :contract_type => params[:contract_type], :job_type => params[:job_type], 
        :shift => params[:shift_id], :page => 1, :size => 20}, :Authorization => Rails.application.config.api_authorization, "Content-Type" => "application/json"}
	    
	  job_roles_get = RestClient.get Rails.application.config.api_server_url + "job_roles", {:Authorization => Rails.application.config.api_authorization,
        "Content-Type" => "application/json"}

	  @jobs = Hash.from_xml(jobs_get)

	  @job_roles = Hash.from_xml(job_roles_get)

	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'home'
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/show.html.erb
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script>
function initialize() {
  // var myLatlng = new google.maps.LatLng(51.508742,-0.120850);
  var myLatlng = new google.maps.LatLng(<%= @job["location"] %>);
  var mapProp = {
    center:myLatlng,
    zoom: 13,
    mapTypeId:google.maps.MapTypeId.ROADMAP
  };
  var map=new google.maps.Map(document.getElementById("googleMap"), mapProp);
  var marker = new google.maps.Marker({
    position: myLatlng,
    map: map,
    title: "<%= @job["job_role"]["slug"] != "OTHER" ? @job["job_role"]["name"] : @job["other_job_role"] %>"
  });
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div class="yp-header">
<div class="yp-header-left-btn">
        <a href="<%= jobs_path %>"><div class="yp-header-left-btn-icon"><%= image_tag "yp-list-header-back-icon.png", width: "13", height: "22" %></div></a>
  </div>
   <div class="yp-header-logo">
        <a href="<%=root_path %>"><div class="yp-header-logo-icon"><%= image_tag "yp-home-yapjobs-logo.png" %></div></a>
    </div>
    <div class="yp-header-next-btn">
<!--      <a href="<%= search_index_path %>"><div class="yp-header-next-btn-icon"><%= image_tag "yp-list-header-setting-icon.png", width: "23", height: "23" %></div></a> -->
        <%= form_tag('/search/list', method: "get", class: "setting-button") do %>
            <%= hidden_field_tag "distance", "50" %>
            <%= hidden_field_tag "current_position" %>
            <%= hidden_field_tag "job_role_id", "-1" %>
            <%= hidden_field_tag "hourly_rate", "5.13" %>
            <%= hidden_field_tag "shift_id", "-1" %>
            <%= hidden_field_tag "job_type", "-1" %>
            <%= hidden_field_tag "contract_type", "-1" %>
            <%= image_submit_tag("yp-list-header-setting-icon.png", width: "23", height: "23") %>
        <% end %>
    </div>
    <div class="clearBoth"></div>
</div>


<div id="googleMap" style="width:100%;height:125px;"></div>
<div class="yp-job-section">
<div class="yp-job-title"><%= @job["job_role"]["slug"] != "OTHER" ? @job["job_role"]["name"] : @job["other_job_role"] %></div>
<div class="yp-job-details">
Start: <%= @job["start_date"].strftime('%b %d, %Y') %><br>
Role: <%= (@job["job_type"] == true) ? 'Part Time' : 'Full Time' %><br>
Shift: <%= 'Day' if @job["shift_id"] == 1 %><%= 'Evening' if @job["shift_id"] == 2 %><%= 'Night' if @job["shift_id"] == 3 %><br>
Hourly Rate: £ <%= @job["hourly_rate"].to_f.round(2) %>/Hour<br>
Contract Type: <%= (@job["contract_type"] == true) ? 'Permanent' : 'Temporary' %><br>
About Job: <%= @job["about_job"] %><br>
Responsibilities:
    <br/>
     <%- @job["job_responsibilities"].each do |job_responsibility| %>
        <%= job_responsibility["name"] %>
     <%- end %>

</div>
<div class="yp-job-hire-manager-label">Hiring Manager</div>
<div class="yp-job-hire-manager-title"><%= @job["hiring_manager"] %></div>
</div>
<a href="https://itunes.apple.com/us/app/yapjobs/id948582939?mt=8" onClick="ga('send','event','iPhone app','https://itunes.apple.com/us/app/yapjobs/id948582939?ls=1&mt=8')" ><div class="yp-job-apply-now-btn">Apply Now</div></a>
<br>
<!--
<div class="yp-job-section">You Might also be interested in</div>


<a href="job-b.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">        
        <= image_tag "yp-list-left-icon-1.png", width: "26", height: "27" %>
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Bartender</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-c.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Cook.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Chef / Cook</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-w.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Waiter.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Waiter / Waitress</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-r.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Receptionist.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Receptionist</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-s.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Security.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Security Guard</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-cl.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Cleaner.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Cleaner</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<br>
<br>
<br>

<script>
  $(function() {
    $( "#slider1" ).slider();
    $( "#slider2" ).slider();
  });
  </script>
-->










<!--
<script
src="http://maps.googleapis.com/maps/api/js">
</script>
<script>
function initialize() {
  var mapProp = {
    center:new google.maps.LatLng(51.508742,-0.120850),
    zoom:5,
    mapTypeId:google.maps.MapTypeId.ROADMAP
  };
  var map=new google.maps.Map(document.getElementById("googleMap"), mapProp);
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div class="yp-header">
<div class="yp-header-left-btn">
        <a href="<%= jobs_path %>"><div class="yp-header-left-btn-icon"><= image_tag "yp-list-header-back-icon.png", width: "13", height: "22" %></div></a>
  </div>
   <div class="yp-header-logo">
        <div class="yp-header-logo-icon"><= image_tag "yp-home-yapjobs-logo.png" %></div>
    </div>
    <div class="yp-header-next-btn">
     <a href="set.html"><div class="yp-header-next-btn-icon"><= image_tag "yp-list-header-setting-icon.png", width: "23", height: "23" %></div></a>
    </div>
    <div class="clearBoth"></div>
</div>


<div id="googleMap" style="width:100%;height:125px;"></div>
<div class="yp-job-section">
<div class="yp-job-title">Bartender</div>
<div class="yp-job-details"> 
Start: May 11, 2015<br>
Role: Part Time<br>
Shift: Day<br>
Hourly Rate: £6.50/Hour<br>
Contract Type: Temporary<br>
Responsibilities:
</div>
<div class="yp-job-hire-manager-label">Hiring Manager</div>
<div class="yp-job-hire-manager-title">Best Men</div>
</div>
<a href="https://itunes.apple.com/us/app/yapjobs/id948582939?mt=8"><div class="yp-job-apply-now-btn">Apply Now</div></a>
<br>
<div class="yp-job-section">You Might also be interested in</div>


<a href="job-b.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">        
        <= image_tag "yp-list-left-icon-1.png", width: "26", height: "27" %>
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Bartender</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-c.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Cook.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Chef / Cook</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-w.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Waiter.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Waiter / Waitress</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-r.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Receptionist.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Receptionist</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-s.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Security.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Security Guard</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<a href="job-cl.html">
<div class="yp-list">
    <div class="yp-list-left">
        <div class="yp-list-left-icon">
        <img src="images/yp-list-left-icon-Cleaner.png" width="26" height="27" alt="">
        </div>
  </div>
    <div class="yp-list-content">
        <div class="yp-list-content-job-title">Cleaner</div>
            <div class="yp-list-content-address">Belgrave Road London</div>
                <div class="yp-list-content-footer">
                <div class="yp-list-content-footer-distance">1 miles away</div>
                <div class="yp-list-content-footer-salary">6.5 ph</div>
                <div class="clearBoth"></div>
            </div>
    </div>
    <div class="clearBoth"></div>

</div>
</a>
<br>
<br>
<br>

 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yapjobs Mobile Version</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" type="image/png" href="favicon.png?v=2"/>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
  <meta name="apple-itunes-app" content="app-id=948582939, affiliate-data=myAffiliateData, app-argument=https://itunes.apple.com/us/app/yapjobs/id948582939?ls=1&mt=8">

  <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      
      ga('create', '#{ENV["GA_CODE"]}', 'auto');
      ga('send', 'pageview');
  </script>
</head>
<body>
	<%= yield %>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;signed_in=false&amp;libraries=places" type="text/javascript"></script>
    
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yapjobs Mobile Version</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-itunes-app" content="app-id=948582939, affiliate-data=myAffiliateData, app-argument=https://itunes.apple.com/us/app/yapjobs/id948582939?ls=1&mt=8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" type="image/png" href="favicon.png?v=2"/>

  <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      
      ga('create', '#{ENV["GA_CODE"]}', 'auto');
      ga('send', 'pageview');
  </script>
</head>
<body class="yp-home-page-bg">
  <div class="yp-home-download-app-store">
  	<a href="https://itunes.apple.com/us/app/yapjobs/id948582939?mt=8">Download From <span>App Store</span></a>
  </div>
  <div class="yp-home-yapjobs-logo"></div>
  <div class="yp-home-tagline">
    YapJobs make finding and applying <br>for jobs simple, easy and fun.
    <div class="bullets">
      <div class="dots"> <%= image_tag "dot-grey.png", class:'doots' %></div>
      <div class="dots"> <%= image_tag "dot-green.png", class:'doots' %></div>
      <div class="dots"> <%= image_tag "dot-grey.png", class:'doots' %></div>
    </div>
  </div>
  <%= form_tag(jobs_path, method: "get") do %>
    <%= hidden_field_tag "current_position" %>
    <%= submit_tag "View Jobs", class: 'yp-home-view-job' %>
  <%- end %>

<!--   <a href="<%= jobs_path %>">
    <div class="yp-home-view-job">View Jobs</div>
  </a> -->

  <div class="yp-home-fullsite-link">
    <a href="http://www.yapjobs.com/">Switch to full site</a>
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;signed_in=false&amp;libraries=places" type="text/javascript">
  </script> 

  </body>
</html>